### ISSUE TITLE
[NEW function] download_favorites

### ISSUE THREAD

**Issue by LynnPallemaerts** [inbo/fistools#19]
## Voorstel functie naam "download_favorites()"
Based on the script `fis-projecten/Grofwild/Drongengoed/Script/download_favorites.R`

## Functionality
- [ ] Download all favorited camera trap pictures from a given project to the users's hard drive

## Checklist
- [x] maak een nieuw R-bestand 
- [x] sla het R bestand op onder `./R` met filenaam is gelijk aan functienaam
- [x] voorzie een functie titel met `#'` op regel 1 van je script
- [x] voorzie een auteur met `#' @author`
- [x] voorzie een beschrijving met `#' @description`
- [x] voorzie uitleg over de input parameter(s) met `#' @param name`
- [x] voorzie uitleg over de output van de functie met `#' @returns`
- [x] voorzie minstens 1 voorbeeld van het gebruik van de functie dmv `#' @examples`
- [ ] voorzie de export - tag dmv `#' @export` ([#14](https://github.com/inbo/fistools/issues/14))
- [ ] voer `usethis::use_package("packagename", min_version = TRUE)` uit in de console voor iedere package die je gebruikt. 
- [ ] voer `roxygen2::roxygenise()` uit in de console
- [ ] voer `devtools::check()` uit in de console
- [ ] los eventuele errors, warnings en notes<sup>1</sup> op
- [ ] maak een pull request met @soriadelva of @SanderDevisscher en eventueel andere relevante gebruikers als reviewer.

*<sup>1</sup>in de mate van het mogelijke*

**Comment by SanderDevisscher** [comment]
ivm je export path:

paste0("C:/Users/", Sys.getenv("username"), "/Pictures/", ...

of "../../../Pictures"

of met een export folder parameter met een van bovenstaande opties als default

**Comment by SanderDevisscher** [comment]
@LynnPallemaerts kan je ook een voorbeeld dataset (subset of random sample van drongengoed zip) toevoegen? Ik zal ze dan ook gebruiken in de voorbeelden van download_media (#6)
