### ISSUE TITLE
[NEW Function] Update GRTS functions to sf

### ISSUE THREAD

**Issue by LynnPallemaerts** [inbo/fistools#22]
## Checklist
- [x] copy [apply_grtsdb.R](https://github.com/inbo/fis-projecten/blob/master/Functions/apply_grtsdb.R) from fis-projecten to "./R"
- [x] copy [cleanup_sqlite.R](https://github.com/inbo/fis-projecten/blob/master/Functions/cleanup_sqlite.R) from fis-projecten to "./R"
- [x] copy [UUID_List.R](https://github.com/inbo/backoffice-wild-analyse/blob/master/Functies/UUID_List.R) from backoffice to "./R"
- [x] remove usages of `rgdal` and other `sp` related packages
- [x] voorzie een functie titel met `#'` op regel 1 van je script
- [x] voorzie een auteur met `#' @author`
- [x] voorzie een beschrijving met `#' @description`
- [x] voorzie uitleg over de input parameter(s) met `#' @param name`
- [x] voorzie uitleg over de output van de functie met `#' @returns`
- [x] voorzie minstens 1 voorbeeld van het gebruik van de functie dmv `#' @examples`
- [x] voorzie de export - tag dmv `#' @export` ([#14](https://github.com/inbo/fistools/issues/14))
- [x] voer `usethis::use_package("packagename", min_version = TRUE)` uit in de console voor iedere package die je gebruikt. 
- [x] voer `roxygen2::roxygenise()` uit in de console
- [ ] voer `devtools::check()` uit in de console
- [ ] los eventuele errors, warnings en notes<sup>1</sup> op
- [ ] maak een pull request met @soriadelva of @SanderDevisscher en eventueel andere relevante gebruikers als reviewer.

*<sup>1</sup>in de mate van het mogelijke*

**Comment by SanderDevisscher** [comment]
I'm having issues with rtools which are delaying finishing this issue
