### ISSUE TITLE
[NEW-FUNCTION] download_media

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/fistools#4]
start from https://github.com/inbo/fis-projecten/blob/master/Functions/download_media.R

- [x] maak een nieuw R-bestand 
- [x] sla het R bestand op onder `./R` met filenaam is gelijk aan functienaam
- [x] voorzie een auteur met `#' @author`
- [x] voorzie een beschrijving met `#' @description`
- [x] voorzie uitleg over de input parameter(s) met `#' @param name`
- [x] voorzie uitleg over de output van de functie met `#' @returns`
- [x] voorzie minstens 1 voorbeeld van het gebruik van de functie dmv `#' @examples`
- [x] voer `roxygen2::roxygenise()` uit in de console
- [x] voer `devtools::check()` uit in de console
- [x] los eventuele errors, warnings en notes<sup>1</sup> op
- [x] maak een pull request met @soriadelva of @SanderDevisscher en eventueel andere relevante gebruikers als reviewer.

*<sup>1</sup>in de mate van het mogelijke*

**Comment by LynnPallemaerts** [comment]
@SanderDevisscher What is this new repo? :-P

Also, I've wanted to edit a script to a function `download_favorites()`, where do I best put this new function?
