### ISSUE TITLE
[NEW function] rename_ct_files

### ISSUE THREAD

**Issue by LynnPallemaerts** [inbo/fistools#84]
## Functionality
- [ ] Function based on `rename_file_names()` from the old `fis-projecten` repo
- [ ] To be used on camera trap pictures (SD cards) when there are more than 9999 pictures present in a deployment
- [ ] Will rename all the files (i.e. photos) by appending folder name (100RECX, 101RECX, etc) to file name (IMG0001, IMG0002, etc)
- [ ] Needed to upload in Agouti, as it considers pictures with the same file name as duplicates

## Checklist
- [x] maak een nieuw R-bestand 
- [x] sla het R bestand op onder `./R` met filenaam is gelijk aan functienaam
- [x] voorzie een functie titel met `#'` op regel 1 van je script
- [x] voorzie een auteur met `#' @author`
- [x] voorzie een beschrijving met `#' @description`
- [x] voorzie uitleg over de input parameter(s) met `#' @param name`
- [x] voorzie uitleg over de output van de functie met `#' @returns`
- [x] voorzie minstens 1 voorbeeld van het gebruik van de functie dmv `#' @examples`
- [x] voorzie de export - tag dmv `#' @export` ([#14](https://github.com/inbo/fistools/issues/14))
- [x] voer `usethis::use_package("packagename", min_version = TRUE)` uit in de console voor iedere package die je gebruikt. 
- [x] voer `roxygen2::roxygenise()` uit in de console
- [x] voer `devtools::check()` uit in de console
- [x] los eventuele errors, warnings en notes<sup>1</sup> op
- [ ] increment versie dmv `usethis::use_version(which = "minor")`<sup>2</sup>
- [x] maak een pull request met @soriadelva of @SanderDevisscher en eventueel andere relevante gebruikers als reviewer.

*<sup>1</sup>in de mate van het mogelijke*

*<sup>2</sup>als je meer dan 5 functies en/of datasets in één pull request veranderd hebt gebruik: `usethis::use_version(which = "major")`*

**Comment by SanderDevisscher** [comment]
@LynnPallemaerts voor het voorbeeld (`#' @examples`) stel ik voor dat je een voorbeeld (een deployment met meer dan 9999 foto's) zipt en op de drive zet. en vervolgens `fistools::download_gdrive_when_missing()` en `unzip` gebruikt om de foto's lokaal te krijgen.

**Comment by LynnPallemaerts** [comment]
@SanderDevisscher Voor de @example heb ik nu gewoon op de juiste plaats twee mapjes geplaatst met enkele foto's. Is dat goed genoeg zo?

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Voor de example heb ik nu gewoon op de juiste plaats twee mapjes geplaatst met enkele foto's. Is dat goed genoeg zo?

liever niet, de data folder is voor datapackages .rda/.rds

**Comment by LynnPallemaerts** [comment]
@SanderDevisscher Nu goed?

**Comment by SanderDevisscher** [comment]
@LynnPallemaerts bijna 😉 Nu nog `tempfile(fileext = ".zip")` als destfile gebruiken. zo voorkom je dat iemand met verwarde kop de bestanden toch terug upload.

**Comment by jimcasaer** [comment]
@SanderDevisscher @LynnPallemaerts even stomme vraag maar wat is/was er fout de oude functie ?

- [ ]

**Comment by LynnPallemaerts** [comment]
@SanderDevisscher Wat doet `package::function()` ook alweer

**Comment by LynnPallemaerts** [comment]
@jimcasaer absoluut niets, maar die was niet mee verhuisd, dus nu even wel. Heb hem gewoon even hernoemd

> @SanderDevisscher @LynnPallemaerts even stomme vraag maar wat is/was er fout de oude functie ?
> 
> * [ ]

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Wat doet `package::function()` ook alweer

specificeren dat de functie van de gespecificeerde package gebruikt dient te worden zonder de volledige package in te laden.

**Comment by LynnPallemaerts** [comment]
@SanderDevisscher Aaaah wanneer ik de functie de eerste keer definieer, zoals bv `dplyr::filter` ?

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Aaaah wanneer ik de functie de eerste keer definieer, zoals bv `dplyr::filter` ?

nope iedere keer als je `dplyr::filter()` gebruikt
